name: Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Create release pull request or tag/release
        uses: changesets/action@v2
        with:
          version-script: npm run version
          publish-script: npm run release
          create-github-releases: true
          commit-message: "chore: version packages"
          pr-title: "chore: version packages"
          github-token: ${{ secrets.GITHUB_TOKEN }}
